AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 instance using cloudformation"

Parameters: 
  serverType:
    Description: "EC2 Server Type"
    Type: String
    Default: "LinuxServer"
    AllowedValues:
      - "LinuxServer"
      - "LinuxWebServer"
  instanceType:
    Description: "EC2 Instance Type"
    Type: String
    Default: "t3.micro"
    AllowedValues:
      - "t3.micro"
      - "t3.small"
  vpcId:
    Description: "VPC ID"
    Type: String
    Default: "vpc-0ad8976c3063a8d73"
  keyPairName:
    Description: "EC2 KeyPair Name"
    Type: String
    Default: "aws-trn-2025"

Mappings:
  ec2AMI:
    LinuxServer:
      amiId: "ami-0341d95f75f311023"
    LinuxWebServer:
      amiId: "ami-0642e14cf687cc7d0"

Conditions:
  isLinuxServer: !Equals
    - !Ref serverType
    - LinuxWebServer

Resources: 
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8
      ImageId: 
        Fn::FindInMap:
          - ec2AMI
          - !Ref serverType
          - amiId
      InstanceType: !Ref instanceType
      KeyName: !Ref keyPairName
      SecurityGroupIds: 
        - !GetAtt ec2SecurityGroup.GroupId
        - !If 
            - isLinuxServer
            - !GetAtt ec2WebSecurityGroup.GroupId
            - !Ref "AWS::NoValue"

  ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Server Security Group" # Required
      GroupName: "cfnLinuxSecGroup"
      SecurityGroupEgress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all outbound"
          FromPort: -1
          IpProtocol: "-1"
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: !Ref vpcId

  ec2WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: isLinuxServer
    Properties:
      GroupDescription: "CFN Linux Web Server Security Group" # Required
      GroupName: "cfnLinuxWebSecGroup"
      SecurityGroupEgress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all outbound"
          FromPort: -1
          IpProtocol: "-1"
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow HTTP"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
      VpcId: !Ref vpcId