AWSTemplateFormatVersion: 2010-09-09

Description: "Sample S3 bucket using cloud formation"

Parameters:
  s3BucketName:
    Type: String
    Description: "The S3 Bucket Name"
    Default: "jlrt-trn-mycfn-bucket"

Resources: 
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref s3BucketName

