AWSTemplateFormatVersion: 2010-09-09
Description: "Sample SQS Queue using CFN"

Parameters: 
  queueName:
    Description: "SQS Queue Name"
    Type: String
    Default: "s3EventsQueueCfn"

Resources: 
  primaryQue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref queueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt deadletterQue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 10

  deadletterQue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref queueName, "DLQ"] ]
      VisibilityTimeout: 10